steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n:latest', '-f', 'deployments/n8n/Dockerfile', 'deployments/n8n']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n:latest']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'n8n'
      - '--image=gcr.io/$PROJECT_ID/n8n:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=8080'
      - '--timeout=300'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=supply-chain-talent-connect:us-central1:supply-postgres-micro'
      - '--set-env-vars=N8N_HOST=0.0.0.0,N8N_PORT=8080,N8N_PROTOCOL=https,N8N_PUBLIC_URL=https://n8n.bradjohnson.ai,N8N_EDITOR_BASE_URL=https://n8n.bradjohnson.ai,WEBHOOK_URL=https://n8n.bradjohnson.ai,N8N_PROXY_HOPS=1,NODE_ENV=production,N8N_DEFAULT_BINARY_DATA_MODE=s3,S3_ENDPOINT=https://storage.googleapis.com,S3_FORCE_PATH_STYLE=true,S3_REGION=auto,S3_BUCKET_NAME=${_N8N_GCS_BUCKET},EXECUTIONS_MODE=main,N8N_RUNNERS_ENABLED=false,N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true,N8N_BLOCK_ENV_ACCESS_IN_NODE=false,GENERIC_TIMEZONE=America/New_York,DB_TYPE=postgresdb,DB_POSTGRESDB_DATABASE=n8n_db,DB_POSTGRESDB_HOST=/cloudsql/supply-chain-talent-connect:us-central1:supply-postgres-micro,DB_POSTGRESDB_USER=n8n,DB_POSTGRESDB_PORT=5432'
      - '--set-secrets=DB_POSTGRESDB_PASSWORD=n8n-db-password:latest,N8N_ENCRYPTION_KEY=n8n-encryption-key:latest,S3_ACCESS_KEY=n8n-s3-access-key:latest,S3_ACCESS_SECRET=n8n-s3-secret-key:latest'
      
timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _N8N_GCS_BUCKET: n8n-binary-data-supply-chain-talent-connect
