steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n:latest', '-f', 'deployments/n8n/Dockerfile', 'deployments/n8n']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n:latest']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'n8n'
      - '--image=gcr.io/$PROJECT_ID/n8n:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--port=8080'
      - '--timeout=300'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=supply-chain-talent-connect:us-central1:supply-postgres-micro'
      - '--set-env-vars=N8N_PORT=8080,N8N_DATABASE_TYPE=postgresdb,N8N_POSTGRES_DATABASE=n8n_db,N8N_POSTGRES_HOST=/cloudsql/supply-chain-talent-connect:us-central1:supply-postgres-micro,N8N_POSTGRES_USER=n8n,N8N_PUBLIC_URL=https://n8n-ynj5h3auha-uc.a.run.app,N8N_PROTOCOL=https,N8N_EDITOR_BASE_URL=https://n8n-ynj5h3auha-uc.a.run.app,N8N_WEBHOOK_BASE_URL=https://n8n-ynj5h3auha-uc.a.run.app,N8N_PROXY_HOPS=1,NODE_ENV=production,N8N_DEFAULT_BINARY_DATA_MODE=filesystem,N8N_USER_FOLDER=/tmp/.n8n,EXECUTIONS_MODE=main,GENERIC_TIMEZONE=America/New_York'
      - '--set-secrets=N8N_POSTGRES_PASSWORD=n8n-db-password:latest,N8N_ENCRYPTION_KEY=n8n-encryption-key:latest'
      
timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY