steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/listmonk:latest', '.']
    dir: 'deployments/listmonk'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/listmonk:latest']
  
  # Deploy container image to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'listmonk'
    - '--image'
    - 'gcr.io/$PROJECT_ID/listmonk:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '2'
    - '--min-instances'
    - '0'
    - '--port'
    - '9000'
    - '--timeout'
    - '300'
    - '--add-cloudsql-instances'
    - 'supply-chain-talent-connect:us-central1:supply-postgres-micro'
    - '--set-secrets'
    - 'DATABASE_PASSWORD=db-password:latest,LISTMONK_db__password=db-password:latest'

# Build timeout
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY