name: supply-stack

networks:
  proxy:
    external: true

services:
  supply:
    image: ghcr.io/supply-chain-talent-connect/supply:latest
    container_name: supply
    restart: unless-stopped
    env_file: [.env]
    environment:
      TZ: America/Detroit
      NODE_ENV: production
      DIRECTUS_URL: "https://admin.bradjohnson.ai"
      # paste your production webhook if you use it:
      N8N_WEBHOOK_URL: "https://n8n.bradjohnson.ai/webhook/<id>"
    networks: [proxy]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      - com.centurylinklabs.watchtower.enable=true
