# .github/workflows/publish.yml
name: Build & Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR (push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bradjmsu
          password: ${{ secrets.GHCR_PAT }}     # PAT with write:packages (+ repo)
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          build-args: |
            VITE_DIRECTUS_URL=${{ vars.VITE_DIRECTUS_URL }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Unraid over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 68.62.17.254
          port: 2222
          username: ${{ vars.UNRAID_SSH_USER }}
          key: ${{ secrets.UNRAID_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd /mnt/user/supply
            docker login ghcr.io -u bradjmsu -p ${{ secrets.GHCR_READ_PAT }} || exit 1
            docker compose pull supply
            docker compose up -d supply
            docker image prune -f
