name: Update GitHub Actions IP allowlist
on:
  schedule:
    - cron: "17 3 * * *"   # daily
  workflow_dispatch:

jobs:
  gen:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow commit back to repo
    steps:
      - uses: actions/checkout@v4

      - name: Generate IPv4 list from GitHub Meta
        run: |
          set -euo pipefail
          mkdir -p generated
          curl -s https://api.github.com/meta \
          | jq -r '.actions[]' \
          | grep -E '^[0-9]+\.' \
          | sort -u > generated/github-actions-ipv4.txt
          wc -l generated/github-actions-ipv4.txt

      - name: Commit if changed
        run: |
          if ! git diff --quiet generated/github-actions-ipv4.txt; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add generated/github-actions-ipv4.txt
            git commit -m "update GitHub Actions IPv4 allowlist [skip ci]"
            git push
          else
            echo "No changes."
          fi
